export const CONSTANT = { 
    APP_NAME : 'Fuse Initializer',
    VALIDATE_MIN_GROUP : 5,
    VALIDATE_MAX_GROUP : 100,
    VALIDATE_MIN_ARTIFACT : 5,
    VALIDATE_MAX_ARTIFACT : 100,
    VALIDATE_MIN_NAME : 5,
    VALIDATE_MAX_NAME : 100,
    VALIDATE_MIN_DESCRIPTION : 5,
    VALIDATE_MAX_DESCRIPTION : 100,
    VALIDATE_MIN_PACKAGE_NAME : 5,
    VALIDATE_MAX_PACKAGE_NAME : 100,
    VALIDATE_MIN_AUTHOR : 5,
    VALIDATE_MAX_AUTHOR : 100,
    URL_SERVICE_FUSE_INITIALIZER : "https://jsonplaceholder.typicode.com/todos/",
    VALIDATE_MESSAGE_REQUIRED: "is required.",
    VALIDATE_MESSAGE_MIN_LENGTH: "must be at least",
    VALIDATE_MESSAGE_MAX_LENGTH: "must not be greater than "
}